/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.melangeurmodel.ui.internal.MelangeurmodelActivator;

public class MelangeurmodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MelangeurmodelActivator.getInstance().getInjector("org.example.melangeurmodel.Melangeurmodel");
	}

}
