/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.example.melangeurmodel.ui.internal.MelangeurmodelActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MelangeurmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MelangeurmodelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MelangeurmodelActivator activator = MelangeurmodelActivator.getInstance();
		return activator != null ? activator.getInjector(MelangeurmodelActivator.ORG_EXAMPLE_MELANGEURMODEL_MELANGEURMODEL) : null;
	}

}
