/**
 * generated by Xtext 2.18.0.M3
 */
package mixin.ide;

import mixin.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
