/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.melangeurmodel.MelangeurmodelRuntimeModule;
import org.example.melangeurmodel.MelangeurmodelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MelangeurmodelIdeSetup extends MelangeurmodelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MelangeurmodelRuntimeModule(), new MelangeurmodelIdeModule()));
	}
	
}
