/*
 * generated by Xtext 2.18.0.M3
 */
package mixin.ide

import com.google.inject.Guice
import mixin.MyDslRuntimeModule
import mixin.MyDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyDslIdeSetup extends MyDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule, new MyDslIdeModule))
	}
	
}
