/**
 * generated by Xtext 2.18.0.M3
 */
package mixin.myDsl.impl;

import mixin.myDsl.Clean;
import mixin.myDsl.MyDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Clean</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CleanImpl extends InstructionImpl implements Clean
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CleanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CLEAN;
  }

} //CleanImpl
