package com.supanadit.restsuite.component.input;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JTextField;
import java.awt.*;
import javax.swing.*;
public class InputComponent extends JTextField {
    private String placeholder;

    @Override
    protected void paintComponent(final Graphics pG) {
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getFontMetrics");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getInsets");
        analyse.AnalyseLog.analyseLog( "paintComponent", "drawString");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getDisabledTextColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setColor");
        analyse.AnalyseLog.analyseLog( "paintComponent", "setRenderingHint");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "getText");
        analyse.AnalyseLog.analyseLog( "paintComponent", "length");
        analyse.AnalyseLog.analyseLog( "paintComponent", "paintComponent");
        super.paintComponent(pG);
        if (((placeholder == null) || (placeholder.length() == 0)) || (getText().length() > 0)) {
            return;
        }
        final Graphics2D g = ((Graphics2D) (pG));
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setColor(getDisabledTextColor());
        g.drawString(placeholder, getInsets().left, pG.getFontMetrics().getMaxAscent() + getInsets().top);
    }

    public void setPlaceholder(final String s) {
        placeholder = s;
    }
}