/**
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.melangeurmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clean</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getClean()
 * @model
 * @generated
 */
public interface Clean extends Instruction
{
} // Clean
