/**
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.melangeurmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datatype</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Datatype#getName <em>Name</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Datatype#getVarname <em>Varname</em>}</li>
 * </ul>
 *
 * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getDatatype()
 * @model
 * @generated
 */
public interface Datatype extends Instruction
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getDatatype_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Datatype#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Varname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varname</em>' containment reference.
   * @see #setVarname(Variable)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getDatatype_Varname()
   * @model containment="true"
   * @generated
   */
  Variable getVarname();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Datatype#getVarname <em>Varname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Varname</em>' containment reference.
   * @see #getVarname()
   * @generated
   */
  void setVarname(Variable value);

} // Datatype
