/**
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.melangeurmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends EObject
{
} // Instruction
