/**
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.melangeurmodel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelFactory
 * @model kind="package"
 * @generated
 */
public interface MelangeurmodelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "melangeurmodel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/melangeurmodel/Melangeurmodel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "melangeurmodel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MelangeurmodelPackage eINSTANCE = org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl.init();

  /**
   * The meta object id for the '{@link org.example.melangeurmodel.melangeurmodel.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.melangeurmodel.melangeurmodel.impl.ModelImpl
   * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INSTRUCTION = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.melangeurmodel.melangeurmodel.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.melangeurmodel.melangeurmodel.impl.InstructionImpl
   * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.melangeurmodel.melangeurmodel.impl.MoveImpl
   * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getMove()
   * @generated
   */
  int MOVE = 2;

  /**
   * The feature id for the '<em><b>Move</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__MOVE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__TYPE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Qty Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__QTY_CUP = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Qty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__QTY = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__FROM = INSTRUCTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__TO = INSTRUCTION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__FILTER = INSTRUCTION_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__TIME = INSTRUCTION_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link org.example.melangeurmodel.melangeurmodel.impl.DatatypeImpl <em>Datatype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.melangeurmodel.melangeurmodel.impl.DatatypeImpl
   * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getDatatype()
   * @generated
   */
  int DATATYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Varname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__VARNAME = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Datatype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.example.melangeurmodel.melangeurmodel.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.melangeurmodel.melangeurmodel.impl.VariableImpl
   * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.melangeurmodel.melangeurmodel.impl.CupImpl <em>Cup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.melangeurmodel.melangeurmodel.impl.CupImpl
   * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getCup()
   * @generated
   */
  int CUP = 5;

  /**
   * The feature id for the '<em><b>Nr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP__NR = 0;

  /**
   * The number of structural features of the '<em>Cup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.melangeurmodel.melangeurmodel.impl.CleanImpl <em>Clean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.melangeurmodel.melangeurmodel.impl.CleanImpl
   * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getClean()
   * @generated
   */
  int CLEAN = 6;

  /**
   * The number of structural features of the '<em>Clean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLEAN_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.example.melangeurmodel.melangeurmodel.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.melangeurmodel.melangeurmodel.Model#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instruction</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Model#getInstruction()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Instruction();

  /**
   * Returns the meta object for class '{@link org.example.melangeurmodel.melangeurmodel.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.example.melangeurmodel.melangeurmodel.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Move#getMove <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Move</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getMove()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Move();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Move#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getType()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Type();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Move#getQtyCup <em>Qty Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Qty Cup</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getQtyCup()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_QtyCup();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Move#getQty <em>Qty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Qty</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getQty()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Qty();

  /**
   * Returns the meta object for the containment reference '{@link org.example.melangeurmodel.melangeurmodel.Move#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getFrom()
   * @see #getMove()
   * @generated
   */
  EReference getMove_From();

  /**
   * Returns the meta object for the containment reference '{@link org.example.melangeurmodel.melangeurmodel.Move#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getTo()
   * @see #getMove()
   * @generated
   */
  EReference getMove_To();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Move#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filter</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getFilter()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Filter();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Move#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Move#getTime()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Time();

  /**
   * Returns the meta object for class '{@link org.example.melangeurmodel.melangeurmodel.Datatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatype</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Datatype
   * @generated
   */
  EClass getDatatype();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Datatype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Datatype#getName()
   * @see #getDatatype()
   * @generated
   */
  EAttribute getDatatype_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.example.melangeurmodel.melangeurmodel.Datatype#getVarname <em>Varname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Varname</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Datatype#getVarname()
   * @see #getDatatype()
   * @generated
   */
  EReference getDatatype_Varname();

  /**
   * Returns the meta object for class '{@link org.example.melangeurmodel.melangeurmodel.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.example.melangeurmodel.melangeurmodel.Cup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cup</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Cup
   * @generated
   */
  EClass getCup();

  /**
   * Returns the meta object for the attribute '{@link org.example.melangeurmodel.melangeurmodel.Cup#getNr <em>Nr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nr</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Cup#getNr()
   * @see #getCup()
   * @generated
   */
  EAttribute getCup_Nr();

  /**
   * Returns the meta object for class '{@link org.example.melangeurmodel.melangeurmodel.Clean <em>Clean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clean</em>'.
   * @see org.example.melangeurmodel.melangeurmodel.Clean
   * @generated
   */
  EClass getClean();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MelangeurmodelFactory getMelangeurmodelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.example.melangeurmodel.melangeurmodel.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.melangeurmodel.melangeurmodel.impl.ModelImpl
     * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INSTRUCTION = eINSTANCE.getModel_Instruction();

    /**
     * The meta object literal for the '{@link org.example.melangeurmodel.melangeurmodel.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.melangeurmodel.melangeurmodel.impl.InstructionImpl
     * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.melangeurmodel.melangeurmodel.impl.MoveImpl
     * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Move</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__MOVE = eINSTANCE.getMove_Move();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__TYPE = eINSTANCE.getMove_Type();

    /**
     * The meta object literal for the '<em><b>Qty Cup</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__QTY_CUP = eINSTANCE.getMove_QtyCup();

    /**
     * The meta object literal for the '<em><b>Qty</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__QTY = eINSTANCE.getMove_Qty();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE__FROM = eINSTANCE.getMove_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE__TO = eINSTANCE.getMove_To();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__FILTER = eINSTANCE.getMove_Filter();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__TIME = eINSTANCE.getMove_Time();

    /**
     * The meta object literal for the '{@link org.example.melangeurmodel.melangeurmodel.impl.DatatypeImpl <em>Datatype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.melangeurmodel.melangeurmodel.impl.DatatypeImpl
     * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getDatatype()
     * @generated
     */
    EClass DATATYPE = eINSTANCE.getDatatype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATATYPE__NAME = eINSTANCE.getDatatype_Name();

    /**
     * The meta object literal for the '<em><b>Varname</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPE__VARNAME = eINSTANCE.getDatatype_Varname();

    /**
     * The meta object literal for the '{@link org.example.melangeurmodel.melangeurmodel.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.melangeurmodel.melangeurmodel.impl.VariableImpl
     * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.example.melangeurmodel.melangeurmodel.impl.CupImpl <em>Cup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.melangeurmodel.melangeurmodel.impl.CupImpl
     * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getCup()
     * @generated
     */
    EClass CUP = eINSTANCE.getCup();

    /**
     * The meta object literal for the '<em><b>Nr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUP__NR = eINSTANCE.getCup_Nr();

    /**
     * The meta object literal for the '{@link org.example.melangeurmodel.melangeurmodel.impl.CleanImpl <em>Clean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.melangeurmodel.melangeurmodel.impl.CleanImpl
     * @see org.example.melangeurmodel.melangeurmodel.impl.MelangeurmodelPackageImpl#getClean()
     * @generated
     */
    EClass CLEAN = eINSTANCE.getClean();

  }

} //MelangeurmodelPackage
