/**
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.melangeurmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getMove <em>Move</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getType <em>Type</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getQtyCup <em>Qty Cup</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getQty <em>Qty</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getFrom <em>From</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getTo <em>To</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getFilter <em>Filter</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.Move#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends Instruction
{
  /**
   * Returns the value of the '<em><b>Move</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move</em>' attribute.
   * @see #setMove(String)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_Move()
   * @model
   * @generated
   */
  String getMove();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getMove <em>Move</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Move</em>' attribute.
   * @see #getMove()
   * @generated
   */
  void setMove(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Qty Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qty Cup</em>' attribute.
   * @see #setQtyCup(int)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_QtyCup()
   * @model
   * @generated
   */
  int getQtyCup();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getQtyCup <em>Qty Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qty Cup</em>' attribute.
   * @see #getQtyCup()
   * @generated
   */
  void setQtyCup(int value);

  /**
   * Returns the value of the '<em><b>Qty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qty</em>' attribute.
   * @see #setQty(int)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_Qty()
   * @model
   * @generated
   */
  int getQty();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getQty <em>Qty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qty</em>' attribute.
   * @see #getQty()
   * @generated
   */
  void setQty(int value);

  /**
   * Returns the value of the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' containment reference.
   * @see #setFrom(Cup)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_From()
   * @model containment="true"
   * @generated
   */
  Cup getFrom();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getFrom <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' containment reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Cup value);

  /**
   * Returns the value of the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' containment reference.
   * @see #setTo(Cup)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_To()
   * @model containment="true"
   * @generated
   */
  Cup getTo();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getTo <em>To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' containment reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Cup value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' attribute.
   * @see #setFilter(String)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_Filter()
   * @model
   * @generated
   */
  String getFilter();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getFilter <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' attribute.
   * @see #getFilter()
   * @generated
   */
  void setFilter(String value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(int)
   * @see org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage#getMove_Time()
   * @model
   * @generated
   */
  int getTime();

  /**
   * Sets the value of the '{@link org.example.melangeurmodel.melangeurmodel.Move#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(int value);

} // Move
