/*
 * generated by Xtext 2.18.0.M3
 */
package mixin.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import mixin.ide.contentassist.antlr.internal.InternalMyDslParser;
import mixin.services.MyDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getMoveAccess().getFilterAlternatives_7_2_0(), "rule__Move__FilterAlternatives_7_2_0");
			builder.put(grammarAccess.getMoveAccess().getGroup(), "rule__Move__Group__0");
			builder.put(grammarAccess.getMoveAccess().getGroup_7(), "rule__Move__Group_7__0");
			builder.put(grammarAccess.getCupAccess().getGroup(), "rule__Cup__Group__0");
			builder.put(grammarAccess.getCleanAccess().getGroup(), "rule__Clean__Group__0");
			builder.put(grammarAccess.getModelAccess().getInstructionAssignment(), "rule__Model__InstructionAssignment");
			builder.put(grammarAccess.getMoveAccess().getQtyAssignment_1(), "rule__Move__QtyAssignment_1");
			builder.put(grammarAccess.getMoveAccess().getFromAssignment_4(), "rule__Move__FromAssignment_4");
			builder.put(grammarAccess.getMoveAccess().getToAssignment_6(), "rule__Move__ToAssignment_6");
			builder.put(grammarAccess.getMoveAccess().getFilterAssignment_7_2(), "rule__Move__FilterAssignment_7_2");
			builder.put(grammarAccess.getCupAccess().getNrAssignment_1(), "rule__Cup__NrAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
