/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.melangeurmodel.parser.antlr.internal.InternalMelangeurmodelParser;
import org.example.melangeurmodel.services.MelangeurmodelGrammarAccess;

public class MelangeurmodelParser extends AbstractAntlrParser {

	@Inject
	private MelangeurmodelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMelangeurmodelParser createParser(XtextTokenStream stream) {
		return new InternalMelangeurmodelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MelangeurmodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MelangeurmodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
