/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MelangeurmodelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/example/melangeurmodel/parser/antlr/internal/InternalMelangeurmodel.tokens");
	}
}
