/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MelangeurmodelStandaloneSetup extends MelangeurmodelStandaloneSetupGenerated {

	public static void doSetup() {
		new MelangeurmodelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
