/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MelangeurmodelRuntimeModule extends AbstractMelangeurmodelRuntimeModule {
}
