/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMelangeurmodelScopeProvider extends DelegatingScopeProvider {
}
