/**
 * generated by Xtext 2.18.0.M3
 */
package mixin;

import mixin.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
