/**
 * generated by Xtext 2.18.0.M3
 */
package mixin.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clean</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mixin.myDsl.MyDslPackage#getClean()
 * @model
 * @generated
 */
public interface Clean extends Instruction
{
} // Clean
