/**
 * generated by Xtext 2.18.0.M3
 */
package mixin.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cup</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mixin.myDsl.Cup#getNr <em>Nr</em>}</li>
 * </ul>
 *
 * @see mixin.myDsl.MyDslPackage#getCup()
 * @model
 * @generated
 */
public interface Cup extends EObject
{
  /**
   * Returns the value of the '<em><b>Nr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nr</em>' attribute.
   * @see #setNr(int)
   * @see mixin.myDsl.MyDslPackage#getCup_Nr()
   * @model
   * @generated
   */
  int getNr();

  /**
   * Sets the value of the '{@link mixin.myDsl.Cup#getNr <em>Nr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nr</em>' attribute.
   * @see #getNr()
   * @generated
   */
  void setNr(int value);

} // Cup
