/**
 * generated by Xtext 2.18.0.M3
 */
package mixin.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mixin.myDsl.Model#getInstruction <em>Instruction</em>}</li>
 * </ul>
 *
 * @see mixin.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Instruction</b></em>' containment reference list.
   * The list contents are of type {@link mixin.myDsl.Instruction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instruction</em>' containment reference list.
   * @see mixin.myDsl.MyDslPackage#getModel_Instruction()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getInstruction();

} // Model
