/**
 * generated by Xtext 2.18.0.M3
 */
package mixin.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mixin.myDsl.Move#getQty <em>Qty</em>}</li>
 *   <li>{@link mixin.myDsl.Move#getFrom <em>From</em>}</li>
 *   <li>{@link mixin.myDsl.Move#getTo <em>To</em>}</li>
 *   <li>{@link mixin.myDsl.Move#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @see mixin.myDsl.MyDslPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends Instruction
{
  /**
   * Returns the value of the '<em><b>Qty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qty</em>' attribute.
   * @see #setQty(int)
   * @see mixin.myDsl.MyDslPackage#getMove_Qty()
   * @model
   * @generated
   */
  int getQty();

  /**
   * Sets the value of the '{@link mixin.myDsl.Move#getQty <em>Qty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qty</em>' attribute.
   * @see #getQty()
   * @generated
   */
  void setQty(int value);

  /**
   * Returns the value of the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' containment reference.
   * @see #setFrom(Cup)
   * @see mixin.myDsl.MyDslPackage#getMove_From()
   * @model containment="true"
   * @generated
   */
  Cup getFrom();

  /**
   * Sets the value of the '{@link mixin.myDsl.Move#getFrom <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' containment reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Cup value);

  /**
   * Returns the value of the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' containment reference.
   * @see #setTo(Cup)
   * @see mixin.myDsl.MyDslPackage#getMove_To()
   * @model containment="true"
   * @generated
   */
  Cup getTo();

  /**
   * Sets the value of the '{@link mixin.myDsl.Move#getTo <em>To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' containment reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Cup value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' attribute.
   * @see #setFilter(String)
   * @see mixin.myDsl.MyDslPackage#getMove_Filter()
   * @model
   * @generated
   */
  String getFilter();

  /**
   * Sets the value of the '{@link mixin.myDsl.Move#getFilter <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' attribute.
   * @see #getFilter()
   * @generated
   */
  void setFilter(String value);

} // Move
