/**
 * generated by Xtext 2.18.0.M3
 */
package mixin.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mixin.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.MyDsl.mixin";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = mixin.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link mixin.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.myDsl.impl.ModelImpl
   * @see mixin.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INSTRUCTION = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mixin.myDsl.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.myDsl.impl.InstructionImpl
   * @see mixin.myDsl.impl.MyDslPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mixin.myDsl.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.myDsl.impl.MoveImpl
   * @see mixin.myDsl.impl.MyDslPackageImpl#getMove()
   * @generated
   */
  int MOVE = 2;

  /**
   * The feature id for the '<em><b>Qty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__QTY = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__FROM = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__TO = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__FILTER = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link mixin.myDsl.impl.CupImpl <em>Cup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.myDsl.impl.CupImpl
   * @see mixin.myDsl.impl.MyDslPackageImpl#getCup()
   * @generated
   */
  int CUP = 3;

  /**
   * The feature id for the '<em><b>Nr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP__NR = 0;

  /**
   * The number of structural features of the '<em>Cup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mixin.myDsl.impl.CleanImpl <em>Clean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.myDsl.impl.CleanImpl
   * @see mixin.myDsl.impl.MyDslPackageImpl#getClean()
   * @generated
   */
  int CLEAN = 4;

  /**
   * The number of structural features of the '<em>Clean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLEAN_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link mixin.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see mixin.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link mixin.myDsl.Model#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instruction</em>'.
   * @see mixin.myDsl.Model#getInstruction()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Instruction();

  /**
   * Returns the meta object for class '{@link mixin.myDsl.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see mixin.myDsl.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link mixin.myDsl.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see mixin.myDsl.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link mixin.myDsl.Move#getQty <em>Qty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Qty</em>'.
   * @see mixin.myDsl.Move#getQty()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Qty();

  /**
   * Returns the meta object for the containment reference '{@link mixin.myDsl.Move#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see mixin.myDsl.Move#getFrom()
   * @see #getMove()
   * @generated
   */
  EReference getMove_From();

  /**
   * Returns the meta object for the containment reference '{@link mixin.myDsl.Move#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see mixin.myDsl.Move#getTo()
   * @see #getMove()
   * @generated
   */
  EReference getMove_To();

  /**
   * Returns the meta object for the attribute '{@link mixin.myDsl.Move#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filter</em>'.
   * @see mixin.myDsl.Move#getFilter()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Filter();

  /**
   * Returns the meta object for class '{@link mixin.myDsl.Cup <em>Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cup</em>'.
   * @see mixin.myDsl.Cup
   * @generated
   */
  EClass getCup();

  /**
   * Returns the meta object for the attribute '{@link mixin.myDsl.Cup#getNr <em>Nr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nr</em>'.
   * @see mixin.myDsl.Cup#getNr()
   * @see #getCup()
   * @generated
   */
  EAttribute getCup_Nr();

  /**
   * Returns the meta object for class '{@link mixin.myDsl.Clean <em>Clean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clean</em>'.
   * @see mixin.myDsl.Clean
   * @generated
   */
  EClass getClean();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mixin.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.myDsl.impl.ModelImpl
     * @see mixin.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INSTRUCTION = eINSTANCE.getModel_Instruction();

    /**
     * The meta object literal for the '{@link mixin.myDsl.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.myDsl.impl.InstructionImpl
     * @see mixin.myDsl.impl.MyDslPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link mixin.myDsl.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.myDsl.impl.MoveImpl
     * @see mixin.myDsl.impl.MyDslPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Qty</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__QTY = eINSTANCE.getMove_Qty();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE__FROM = eINSTANCE.getMove_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE__TO = eINSTANCE.getMove_To();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__FILTER = eINSTANCE.getMove_Filter();

    /**
     * The meta object literal for the '{@link mixin.myDsl.impl.CupImpl <em>Cup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.myDsl.impl.CupImpl
     * @see mixin.myDsl.impl.MyDslPackageImpl#getCup()
     * @generated
     */
    EClass CUP = eINSTANCE.getCup();

    /**
     * The meta object literal for the '<em><b>Nr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUP__NR = eINSTANCE.getCup_Nr();

    /**
     * The meta object literal for the '{@link mixin.myDsl.impl.CleanImpl <em>Clean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.myDsl.impl.CleanImpl
     * @see mixin.myDsl.impl.MyDslPackageImpl#getClean()
     * @generated
     */
    EClass CLEAN = eINSTANCE.getClean();

  }

} //MyDslPackage
