/*
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MelangeurmodelUiModule extends AbstractMelangeurmodelUiModule {

	public MelangeurmodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
