/*
 * generated by Xtext 2.18.0.M3
 */
package mixin.ui.tests;

import com.google.inject.Injector;
import mixin.ui.internal.MixinActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MixinActivator.getInstance().getInjector("mixin.MyDsl");
	}

}
