/**
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.melangeurmodel.impl;

import org.eclipse.emf.ecore.EClass;

import org.example.melangeurmodel.melangeurmodel.Clean;
import org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Clean</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CleanImpl extends InstructionImpl implements Clean
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CleanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MelangeurmodelPackage.Literals.CLEAN;
  }

} //CleanImpl
