/**
 * generated by Xtext 2.23.0
 */
package org.example.melangeurmodel.melangeurmodel.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.melangeurmodel.melangeurmodel.Cup;
import org.example.melangeurmodel.melangeurmodel.MelangeurmodelPackage;
import org.example.melangeurmodel.melangeurmodel.Move;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getMove <em>Move</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getQtyCup <em>Qty Cup</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getQty <em>Qty</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getFrom <em>From</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getTo <em>To</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getFilter <em>Filter</em>}</li>
 *   <li>{@link org.example.melangeurmodel.melangeurmodel.impl.MoveImpl#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MoveImpl extends InstructionImpl implements Move
{
  /**
   * The default value of the '{@link #getMove() <em>Move</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMove()
   * @generated
   * @ordered
   */
  protected static final String MOVE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMove() <em>Move</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMove()
   * @generated
   * @ordered
   */
  protected String move = MOVE_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getQtyCup() <em>Qty Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQtyCup()
   * @generated
   * @ordered
   */
  protected static final int QTY_CUP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getQtyCup() <em>Qty Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQtyCup()
   * @generated
   * @ordered
   */
  protected int qtyCup = QTY_CUP_EDEFAULT;

  /**
   * The default value of the '{@link #getQty() <em>Qty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQty()
   * @generated
   * @ordered
   */
  protected static final int QTY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getQty() <em>Qty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQty()
   * @generated
   * @ordered
   */
  protected int qty = QTY_EDEFAULT;

  /**
   * The cached value of the '{@link #getFrom() <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrom()
   * @generated
   * @ordered
   */
  protected Cup from;

  /**
   * The cached value of the '{@link #getTo() <em>To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTo()
   * @generated
   * @ordered
   */
  protected Cup to;

  /**
   * The default value of the '{@link #getFilter() <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilter()
   * @generated
   * @ordered
   */
  protected static final String FILTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFilter() <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilter()
   * @generated
   * @ordered
   */
  protected String filter = FILTER_EDEFAULT;

  /**
   * The default value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected static final int TIME_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected int time = TIME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MelangeurmodelPackage.Literals.MOVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMove()
  {
    return move;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMove(String newMove)
  {
    String oldMove = move;
    move = newMove;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__MOVE, oldMove, move));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getQtyCup()
  {
    return qtyCup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQtyCup(int newQtyCup)
  {
    int oldQtyCup = qtyCup;
    qtyCup = newQtyCup;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__QTY_CUP, oldQtyCup, qtyCup));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getQty()
  {
    return qty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQty(int newQty)
  {
    int oldQty = qty;
    qty = newQty;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__QTY, oldQty, qty));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cup getFrom()
  {
    return from;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFrom(Cup newFrom, NotificationChain msgs)
  {
    Cup oldFrom = from;
    from = newFrom;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__FROM, oldFrom, newFrom);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFrom(Cup newFrom)
  {
    if (newFrom != from)
    {
      NotificationChain msgs = null;
      if (from != null)
        msgs = ((InternalEObject)from).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MelangeurmodelPackage.MOVE__FROM, null, msgs);
      if (newFrom != null)
        msgs = ((InternalEObject)newFrom).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MelangeurmodelPackage.MOVE__FROM, null, msgs);
      msgs = basicSetFrom(newFrom, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__FROM, newFrom, newFrom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Cup getTo()
  {
    return to;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTo(Cup newTo, NotificationChain msgs)
  {
    Cup oldTo = to;
    to = newTo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__TO, oldTo, newTo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTo(Cup newTo)
  {
    if (newTo != to)
    {
      NotificationChain msgs = null;
      if (to != null)
        msgs = ((InternalEObject)to).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MelangeurmodelPackage.MOVE__TO, null, msgs);
      if (newTo != null)
        msgs = ((InternalEObject)newTo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MelangeurmodelPackage.MOVE__TO, null, msgs);
      msgs = basicSetTo(newTo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__TO, newTo, newTo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFilter()
  {
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFilter(String newFilter)
  {
    String oldFilter = filter;
    filter = newFilter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__FILTER, oldFilter, filter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTime()
  {
    return time;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTime(int newTime)
  {
    int oldTime = time;
    time = newTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MelangeurmodelPackage.MOVE__TIME, oldTime, time));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MelangeurmodelPackage.MOVE__FROM:
        return basicSetFrom(null, msgs);
      case MelangeurmodelPackage.MOVE__TO:
        return basicSetTo(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MelangeurmodelPackage.MOVE__MOVE:
        return getMove();
      case MelangeurmodelPackage.MOVE__TYPE:
        return getType();
      case MelangeurmodelPackage.MOVE__QTY_CUP:
        return getQtyCup();
      case MelangeurmodelPackage.MOVE__QTY:
        return getQty();
      case MelangeurmodelPackage.MOVE__FROM:
        return getFrom();
      case MelangeurmodelPackage.MOVE__TO:
        return getTo();
      case MelangeurmodelPackage.MOVE__FILTER:
        return getFilter();
      case MelangeurmodelPackage.MOVE__TIME:
        return getTime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MelangeurmodelPackage.MOVE__MOVE:
        setMove((String)newValue);
        return;
      case MelangeurmodelPackage.MOVE__TYPE:
        setType((String)newValue);
        return;
      case MelangeurmodelPackage.MOVE__QTY_CUP:
        setQtyCup((Integer)newValue);
        return;
      case MelangeurmodelPackage.MOVE__QTY:
        setQty((Integer)newValue);
        return;
      case MelangeurmodelPackage.MOVE__FROM:
        setFrom((Cup)newValue);
        return;
      case MelangeurmodelPackage.MOVE__TO:
        setTo((Cup)newValue);
        return;
      case MelangeurmodelPackage.MOVE__FILTER:
        setFilter((String)newValue);
        return;
      case MelangeurmodelPackage.MOVE__TIME:
        setTime((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MelangeurmodelPackage.MOVE__MOVE:
        setMove(MOVE_EDEFAULT);
        return;
      case MelangeurmodelPackage.MOVE__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case MelangeurmodelPackage.MOVE__QTY_CUP:
        setQtyCup(QTY_CUP_EDEFAULT);
        return;
      case MelangeurmodelPackage.MOVE__QTY:
        setQty(QTY_EDEFAULT);
        return;
      case MelangeurmodelPackage.MOVE__FROM:
        setFrom((Cup)null);
        return;
      case MelangeurmodelPackage.MOVE__TO:
        setTo((Cup)null);
        return;
      case MelangeurmodelPackage.MOVE__FILTER:
        setFilter(FILTER_EDEFAULT);
        return;
      case MelangeurmodelPackage.MOVE__TIME:
        setTime(TIME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MelangeurmodelPackage.MOVE__MOVE:
        return MOVE_EDEFAULT == null ? move != null : !MOVE_EDEFAULT.equals(move);
      case MelangeurmodelPackage.MOVE__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case MelangeurmodelPackage.MOVE__QTY_CUP:
        return qtyCup != QTY_CUP_EDEFAULT;
      case MelangeurmodelPackage.MOVE__QTY:
        return qty != QTY_EDEFAULT;
      case MelangeurmodelPackage.MOVE__FROM:
        return from != null;
      case MelangeurmodelPackage.MOVE__TO:
        return to != null;
      case MelangeurmodelPackage.MOVE__FILTER:
        return FILTER_EDEFAULT == null ? filter != null : !FILTER_EDEFAULT.equals(filter);
      case MelangeurmodelPackage.MOVE__TIME:
        return time != TIME_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (move: ");
    result.append(move);
    result.append(", type: ");
    result.append(type);
    result.append(", qtyCup: ");
    result.append(qtyCup);
    result.append(", qty: ");
    result.append(qty);
    result.append(", filter: ");
    result.append(filter);
    result.append(", time: ");
    result.append(time);
    result.append(')');
    return result.toString();
  }

} //MoveImpl
